### ISSUE TITLE
incorrect buffer type

### ISSUE THREAD

**Issue by marianachi** [valenpe7/sdf2vtk#1]
Hi,

How can I resolve this error:

   convertor.create_vtk_particle_grid(dimension=2, species="electron", subset=None, norm=1.0e-6)
  File "/sdf2vtk/sdf2vtk/sdf2vtk.py", line 109, in create_vtk_particle_grid
    vtk_particle_coords.SetArray(2, self.sdf_particle_z, self.sdf_particle_z.size, False, True)
TypeError: SetArray argument 2: incorrect buffer type, expected d but received f

Thank you in advance.

**Comment by valenpe7** [comment]
Hi @marianachi,

it seems that your data are in single precision, try to add the argument single=True to the method.

**Comment by marianachi** [comment]
Thanks for your prompt answer.

I gave it a try, the error is still there.
This also happened for the fields. The only variable I could convert was the density. 
Unfortunately I cannot attach my sdf file here. But it's a common output from EPOCH.

**Comment by marianachi** [comment]
UPDATE: 
issue resolved for the fields. I changed single to FALSE instead of true. but for the particle variable, like momenta, I still have the error.

Also I have couple of questions: 
- dimension is the depending on the dimension of the simulation?
- what does reduced=False mean?

**Comment by marianachi** [comment]
this is my grid data in x direction.


[selection.txt](https://github.com/valenpe7/sdf2vtk/files/8031020/selection.txt)

**Comment by valenpe7** [comment]
Yes, dimension depends on the simulation and it can be 1, 2, or 3. The parameter reduced is for a down-sampled grid defined by subset and skip_{x, y, z} in the EPOCH input file.

**Comment by valenpe7** [comment]
Hi @marianachi,

please, try it now, I have made a quick fix for the precision of particle coordinates.
