### ISSUE TITLE
AttributeError: module 'sdf' has no attribute 'read'

### ISSUE THREAD

**Issue by huidiwiwi** [valenpe7/sdf2vtk#2]
Hi, I am not able to read the sdf file as you recommended in readme. 
I am not sure how to install sdf? the link your shared is not able to install, i tried pip install sdf, it seems like it is not the correct package. 
many thanks in advance.

**Comment by valenpe7** [comment]
Hi @huidiwiwi,

SDF (Self-Describing File) is a scientific data file format used by EPOCH and other codes (https://github.com/keithbennett/SDF). It is not in the Python Package Index. You may install it as follows:

```
mkdir $dir/SDF
git clone https://github.com/keithbennett/SDF_C.git $dir/SDF/C
cd $dir/SDF/C ; make 
git clone https://github.com/keithbennett/SDF_utilities.git $dir/SDF/utilities
cd $dir/SDF/utilities ; ./build
```

**Comment by huidiwiwi** [comment]
> Hi @huidiwiwi,
> 
> SDF (Self-Describing File) is a scientific data file format used by EPOCH and other codes (https://github.com/keithbennett/SDF). It is not in the Python Package Index. You may install it as follows:
> 
> ```
> mkdir $dir/SDF
> git clone https://github.com/keithbennett/SDF_C.git $dir/SDF/C
> cd $dir/SDF/C ; make 
> git clone https://github.com/keithbennett/SDF_utilities.git $dir/SDF/utilities
> cd $dir/SDF/utilities ; ./build
> ```

I now installed the correct sdf, but it failed to read my .sdf file. Thanks a lot anyway.
